routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes(['register' => false]);

// School
Route::prefix('school')->name('school.')->group(function () {
	Route::get('register', 'SchoolController@create')->name('register');
	Route::post('/', 'SchoolController@store')->name('store');
});

// Default Guard (Web)
Route::middleware(['auth'])->group(function () {
	Route::middleware(['joined'])->group(function () {
		Route::middleware(['level:C|B|A'])->group(function () {
			// Class
			Route::prefix('class')->name('class.')->group(function () {
				Route::post('list', 'StudentClassController@list')->name('list');
				Route::post('close', 'StudentClassController@close')->name('close');
				// Route::post('export', 'StudentClassController@export')->name('export');
				// Route::delete('destroy', 'StudentClassController@destroy')->name('destroy');
				// Student
				Route::prefix('{studentClass}/student')->name('student.')->group(function () {
					Route::post('list', 'StudentController@list')->name('list');
					// Route::post('export', 'StudentController@export')->name('export');
					Route::post('import', 'StudentController@importExcel')->name('import');
					// Route::delete('destroy', 'StudentController@destroy')->name('destroy');
				});
				Route::resource('{studentClass}/student', 'StudentController', ['except' => [
					'destroy',
				]]);
			});
			Route::resource('class', 'StudentClassController', ['parameters' => [
				'class' => 'studentClass'
			], 'except' => [
				'destroy',
			]]);
		
			// Activity
			Route::prefix('activity')->name('activity.')->group(function () {
				Route::post('list', 'ActivityController@list')->name('list');
				// Route::delete('destroy', 'ActivityController@destroy')->name('destroy');
			});
			Route::resource('activity', 'ActivityController', ['except' => [
				'edit', 'update', 'destroy',
			]]);
		
			// Subsidy
			Route::prefix('subsidy')->name('subsidy.')->group(function () {
				Route::post('list', 'SubsidyController@list')->name('list');
				// Route::post('export', 'SubsidyController@export')->name('export');
				// Route::delete('destroy', 'SubsidyController@destroy')->name('destroy');
			});
			Route::resource('subsidy', 'SubsidyController', ['except' => [
				'destroy',
			]]);
		
			// Training
			Route::prefix('training')->name('training.')->group(function () {
				Route::post('list', 'TrainingController@list')->name('list');
				Route::post('preCreate', 'TrainingController@preCreate')->name('preCreate');
				// Route::post('export', 'TrainingController@export')->name('export');
				// Route::delete('destroy', 'TrainingController@destroy')->name('destroy');
			});
			Route::resource('training', 'TrainingController', ['except' => [
				'destroy',
			]]);
		
			// Exam
			Route::prefix('exam')->name('exam.')->group(function () {
				// Exam: readiness
				Route::prefix('readiness')->name('readiness.')->group(function () {
					Route::post('list', 'ExamReadinessController@list')->name('list');
					// Route::post('export', 'ExamReadinessController@export')->name('export');
					// Route::delete('destroy', 'ExamReadinessController@destroy')->name('destroy');
				});
				Route::resource('readiness', 'ExamReadinessController', ['parameters' => [
					'readiness' => 'examReadiness'
				], 'except' => [
					'destroy',
				]]);
			});
		
			// Payment
			Route::prefix('payment')->name('payment.')->group(function () {
				Route::post('list', 'PaymentController@list')->name('list');
				Route::get('{payment}/fill', 'PaymentController@fill')->name('fill');
				Route::put('{payment}/confirm', 'PaymentController@confirm')->name('confirm');
				// Route::post('export', 'PaymentController@export')->name('export');
				// Route::delete('destroy', 'PaymentController@destroy')->name('destroy');
			});
			Route::resource('payment', 'PaymentController', ['except' => [
				'destroy',
			]]);

			// Grant
			Route::prefix('grant')->name('grant.')->group(function () {
				Route::post('list', 'GrantController@list')->name('list');
				// Route::delete('destroy', 'GrantController@destroy')->name('destroy');
			});
			Route::resource('grant', 'GrantController', ['except' => [
				'edit', 'update', 'destroy',
			]]);
		});
	
		Route::middleware(['level:Dalam proses|A'])->group(function () {
			// Attendance
			Route::prefix('attendance')->name('attendance.')->group(function () {
				Route::post('list', 'AttendanceController@list')->name('list');
				Route::delete('destroy', 'AttendanceController@destroy')->name('destroy');
			});
			Route::resource('attendance', 'AttendanceController', ['except' => [
				'destroy',
			]]);
		});
	
		// Home
		Route::get('/', 'HomeController@index')->name('home');
		
		// School
		Route::prefix('school')->name('school.')->group(function () {
			Route::get('edit', 'SchoolController@edit')->name('edit');
			Route::put('update', 'SchoolController@update')->name('update');
		
			// School: document
			Route::prefix('document')->name('document.')->group(function () {
				Route::get('filter/{token?}', 'DocumentController@filter')->name('filter');
				Route::delete('destroy', 'DocumentController@destroy')->name('destroy');
			});
			Route::resource('document', 'DocumentController', ['only' => [
				'store',
			]]);
		
			// School: photo
			Route::prefix('photo')->name('photo.')->group(function () {
				Route::get('filter/{token?}', 'SchoolPhotoController@filter')->name('filter');
				Route::delete('destroy', 'SchoolPhotoController@destroy')->name('destroy');
			});
			Route::resource('photo', 'SchoolPhotoController', ['only' => [
				'store',
			]]);
		});
		Route::resource('school', 'SchoolController', ['only' => [
			'index'
		]]);
		
		// Document
		Route::resource('document', 'DocumentController', ['except' => [
			'destroy',
		]]);
		
		// Teacher
		Route::prefix('teacher')->name('teacher.')->group(function () {
			Route::post('list', 'TeacherController@list')->name('list');
			Route::post('export', 'TeacherController@export')->name('export');
			Route::delete('destroy', 'TeacherController@destroy')->name('destroy');
		});
		Route::resource('teacher', 'TeacherController', ['except' => [
			'destroy',
		]]);
		
		// Account
		Route::prefix('account')->name('account.')->group(function () {
			Route::put('update', 'AccountController@update')->name('update');
		});
		Route::resource('account', 'AccountController', ['parameters' => [
			'account' => 'user'
		], 'only' => [
			'index',
		]]);
	});

	// School
	Route::prefix('school')->name('school.')->group(function () {
		Route::get('set', 'SchoolController@set')->name('set');
		Route::post('set', 'SchoolController@setStore')->name('set.store');
	});
});

/**
 * Admin Guard
 */
Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware(['auth:admin'])->group(function () {
	// Home
    Route::get('/', 'HomeController@index')->name('home');

	// Auth
	/**
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
	Route::post('logout', 'Auth\LoginController@logout')->name('logout');
	**/

    // School
    Route::prefix('school')->name('school.')->group(function () {
    	Route::post('list', 'SchoolController@list')->name('list');
    	Route::post('export', 'SchoolController@export')->name('export');
		Route::delete('destroy', 'SchoolController@destroy')->name('destroy');
		Route::get('bin', 'SchoolController@bin')->name('bin');
		Route::post('binList', 'SchoolController@list')->name('binList');
		Route::post('restore', 'SchoolController@restore')->name('restore');
		Route::delete('destroyPermanently', 'SchoolController@destroyPermanently')->name('destroyPermanently');
		
		// School: document
		Route::prefix('document')->name('document.')->group(function () {
			Route::get('{school}/filter/{token?}', 'DocumentController@filter')->name('filter');
			Route::delete('destroy', 'DocumentController@destroy')->name('destroy');
		});
		Route::resource('{school}/document', 'DocumentController', ['only' => [
			'store',
		]]);

		// School: photo
		Route::prefix('photo')->name('photo.')->group(function () {
			Route::get('{school}/filter/{token?}', 'SchoolPhotoController@filter')->name('filter');
			Route::delete('destroy', 'SchoolPhotoController@destroy')->name('destroy');
		});
		Route::resource('{school}/photo', 'SchoolPhotoController', ['only' => [
			'store',
		]]);

    	// School: comment
    	Route::prefix('comment')->name('comment.')->group(function () {
	    	Route::post('{school}', 'SchoolCommentController@store')->name('store');
	    });
    	/**
    	Route::resource('comment', 'SchoolCommentController', ['only' => [
			'index',
		]]);
		**/
    });
    Route::resource('school', 'SchoolController', ['except' => [
		'destroy',
	]]);

	// Teacher
	Route::prefix('teacher')->name('teacher.')->group(function () {
		Route::post('list', 'TeacherController@list')->name('list');
    	Route::post('export', 'TeacherController@export')->name('export');
		Route::delete('destroy', 'TeacherController@destroy')->name('destroy');
	});
	Route::resource('teacher', 'TeacherController', ['except' => [
		'destroy',
	]]);

	// Class
	Route::prefix('class')->name('class.')->group(function () {
    	Route::post('list', 'StudentClassController@list')->name('list');
    	Route::post('export', 'StudentClassController@export')->name('export');
		Route::delete('destroy', 'StudentClassController@destroy')->name('destroy');
		Route::post('close', 'StudentClassController@close')->name('close');
		Route::post('open', 'StudentClassController@open')->name('open');
		// Student

resources/views/admin/class/create.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
	<div class="col-12">

		@if (session('alert-success'))
			<div class="alert alert-success alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-success') }}
				</div>
			</div>
		@endif

		@if (session('alert-danger'))
			<div class="alert alert-danger alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-danger') }}
				</div>
			</div>
		@endif

		<div class="card card-primary">

			{{ Form::open(['route' => 'admin.class.store', 'files' => true]) }}
				<div class="card-body">
					<div class="row">
						<div class="col-sm-6">
							<fieldset>
                                {{ Form::bsSelect(null, __('School'), 'school_id', $schools, old('school_id'), __('Select'), ['placeholder' => __('Select'), 'required' => '']) }}

                                {{ Form::bsSelect(null, __('Department'), 'department_id', [], old('department_id'), __('Select'), ['placeholder' => __('Select'), 'required' => '']) }}

                                {{ Form::bsText(null, __('Generation'), 'generation', null, __('Generation'), ['disabled' => '']) }}
                            </fieldset>
                        </div>
						<div class="col-sm-6">
							<fieldset>
                                {{ Form::bsText(null, __('School Year'), 'school_year', $schoolYear, __('School Year'), ['disabled' => '']) }}

                                {{ Form::bsText(null, __('Grade'), 'grade', 'Kelas 10', __('Grade'), ['disabled' => '']) }}
                            </fieldset>
					</div>
				</div>
				<div class="card-footer bg-whitesmoke text-center">
					{{ Form::submit(__('Save'), ['name' => 'submit', 'class' => 'btn btn-primary']) }}
					{{ link_to(url()->previous(), __('Cancel'), ['class' => 'btn btn-danger']) }}
				</div>
			{{ Form::close() }}

		</div>
	</div>
</div>
@endsection

@section('script')
<script>
	$(document).ready(function () {
        $('select[name="school_id"]').change(function() {
			$('select[name="department_id"]').html('<option value="">Select</option>').prop('disabled', false);
			if ($(this).val() != '') {
				$.ajax({
					url : "{{ route('get.department') }}",
					type: "POST",
					dataType: "JSON",
					cache: false,
					data: {'_token' : '{{ csrf_token() }}', 'school': $(this).val()},
					success: function(data)
					{
                        if (data.status == true) {
                            $.each(data.result, function(key, value) {
                                $('select[name="department_id"]').append('<option value="'+key+'">'+value+'</option>');
                            });
                            if (Object.keys(data.result).length == 1) {
                                $.each(data.result, function(k, v) {
                                    $('select[name="department_id"]').val(k).change();
                                });;
                                $('select[name="department_id"]').prop('disabled', true);
                            }
                        }
					},
					error: function (jqXHR, textStatus, errorThrown)
					{
						$('select[name="department_id"]').html('<option value="">Select</option>');
					}
				});
			}
		});

		$('select[name="department_id"]').change(function() {
			$('input[name="generation"]').val('');
			if ($(this).val() != '') {
				$.ajax({
					url : "{{ route('get.generationFromClass') }}",
					type: "POST",
					dataType: "JSON",
					cache: false,
					data: {'_token' : '{{ csrf_token() }}', 'school': $('select[name="school_id"]').val(), 'department': $(this).val()},
					success: function(data)
					{
                        if (data.status == true) {
							$('input[name="generation"]').val(data.result);
                        }
					},
					error: function (jqXHR, textStatus, errorThrown)
					{
						$('input[name="generation"]').val('');
					}
				});
			}
		});
	});
</script>
@endsection

resources/views/admin/class/index.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
	<div class="col-12">

		@if (session('alert-success'))
			<div class="alert alert-success alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-success') }}
				</div>
			</div>
		@endif

		@if (session('alert-danger'))
			<div class="alert alert-danger alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-danger') }}
				</div>
			</div>
		@endif

		<div class="card card-primary">
			<div class="card-header">
				@if(auth()->guard('admin')->user()->can('create student_classes'))
					<a href="{{ route('admin.class.create') }}" class="btn btn-icon btn-success" title="{{ __('Create') }}"><i class="fa fa-plus"></i></a>
				@endif
				<button class="btn btn-icon btn-secondary" title="{{ __('Filter') }}" data-toggle="modal" data-target="#filterModal"><i class="fa fa-filter"></i></button>
            	<button class="btn btn-icon btn-secondary" onclick="reloadTable()" title="{{ __('Refresh') }}"><i class="fa fa-sync"></i></i></button>
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table table-sm table-striped" id="table4data">
						<thead>
							<tr>
								<th>
									<div class="checkbox icheck"><label><input type="checkbox" name="selectData"></label></div>
								</th>
								<th>{{ __('Created At') }}</th>
								<th>{{ __('School') }}</th>
								<th>{{ __('Generation') }}</th>
								<th>{{ __('School Year') }}</th>
								<th>{{ __('Department') }}</th>
								<th>{{ __('Status') }}</th>
								<th>{{ __('Action') }}</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
			<div class="card-footer bg-whitesmoke">
				@if (auth()->guard('admin')->user()->can('open student_classes'))
					<button class="btn btn-default btn-sm" name="openData" title="{{ __('Open Class') }}">{{ __('Open') }}</button>
				@endif
				@if (auth()->guard('admin')->user()->can('close student_classes'))
					<button class="btn btn-default btn-sm" name="closeData" title="{{ __('Close Class') }}">{{ __('Close') }}</button>
				@endif
				@if (auth()->guard('admin')->user()->can('delete student_classes'))
					<button class="btn btn-danger btn-sm" name="deleteData" title="{{ __('Delete') }}">{{ __('Delete') }}</button>
				@endif
			</div>
		</div>

	</div>
</div>
@endsection

@section('script')
<script>
	var table;
	$(document).ready(function() {
		table = $('#table4data').DataTable({
			processing: true,
			serverSide: true,
			"ajax": {
				"url": "{{ route('admin.class.list') }}",
				"type": "POST",
				"data": function (d) {
		          d._token = "{{ csrf_token() }}";
				  d.school = $('select[name="school"]').val();
				  d.generation = $('select[name="generation"]').val();
				  d.schoolYear = $('select[name="school_year"]').val();
				  d.department = $('select[name="department"]').val();
		        }
			},
			columns: [
				{ data: 'DT_RowIndex', name: 'DT_RowIndex', 'searchable': false },
				{ data: 'created_at', name: 'created_at' },
				{ data: 'school', name: 'schools.name' },
				{ data: 'generation', name: 'student_classes.generation' },
				{ data: 'school_year', name: 'student_classes.school_year' },
				{ data: 'department', name: 'departments.name' },
				{ data: 'status', name: 'student_classes.closed_at' },
				{ data: 'action', name: 'action' }
			],
			"order": [[ 1, 'desc' ]],
			"columnDefs": [
			{   
          		"targets": [ 0, -1 ], //last column
          		"orderable": false, //set not orderable
      		},
      		],
      		"drawCallback": function(settings) {
      			$('input[name="selectData"], input[name="selectedData[]"]').iCheck({
      				checkboxClass: 'icheckbox_flat-green',
      				radioClass: 'iradio_flat-green',
      				increaseArea: '20%' /* optional */
      			});
      			$('[name="selectData"]').on('ifChecked', function(event){
      				$('[name="selectedData[]"]').iCheck('check');
      			}).on('ifUnchecked', function(event){
      				$('[name="selectedData[]"]').iCheck('uncheck');
      			});
      		},
  		});

		$('select[name="level"]').change(function() {
			if ($(this).val() != '') {
				$('select[name="school"]').html('<option value="">Select</option>');
				$.ajax({
					url : "{{ route('get.school') }}",
					type: "POST",
					dataType: "JSON",
					cache: false,
					data: {'_token' : '{{ csrf_token() }}', 'level' : $(this).val()},
					success: function(data)
					{
						$.each(data.result, function(key, value) {
							$('select[name="school"]').append('<option value="'+key+'">'+value+'</option>');
						});
					},
					error: function (jqXHR, textStatus, errorThrown)
					{
						$('select[name="school"]').html('<option value="">Select</option>');
					}
				});
			}
		});

		$('select[name="school"]').change(function() {
			if ($(this).val() != '') {
				$('select[name="generation"], select[name="school_year"], select[name="department"]').html('<option value="">Select</option>');
				$.ajax({
					url : "{{ route('get.generation') }}",
					type: "POST",
					dataType: "JSON",
					cache: false,
					data: {'_token' : '{{ csrf_token() }}', 'school' : $(this).val()},
					success: function(data)
					{
						$.each(data.result, function(key, value) {
							$('select[name="generation"]').append('<option value="'+key+'">'+value+'</option>');
						});
					},
					error: function (jqXHR, textStatus, errorThrown)
					{
						$('select[name="generation"]').html('<option value="">Select</option>');
					}
				});
				$.ajax({
					url : "{{ route('get.schoolYear') }}",
					type: "POST",
					dataType: "JSON",
					cache: false,
					data: {'_token' : '{{ csrf_token() }}', 'school' : $(this).val()},
					success: function(data)
					{
						$.each(data.result, function(key, value) {
							$('select[name="school_year"]').append('<option value="'+key+'">'+value+'</option>');
						});
					},
					error: function (jqXHR, textStatus, errorThrown)
					{
						$('select[name="school_year"]').html('<option value="">Select</option>');
					}
				});
				$.ajax({
					url : "{{ route('get.department') }}",
					type: "POST",
					dataType: "JSON",
					cache: false,
					data: {'_token' : '{{ csrf_token() }}', 'school' : $(this).val()},
					success: function(data)
					{
						$.each(data.result, function(key, value) {
							$('select[name="department"]').append('<option value="'+key+'">'+value+'</option>');
						});
					},
					error: function (jqXHR, textStatus, errorThrown)
					{
						$('select[name="department"]').html('<option value="">Select</option>');
					}
				});
			}
		});

		$('[name="openData"]').click(function(event) {
			if ($('[name="selectedData[]"]:checked').length > 0) {
				event.preventDefault();
				var selectedData = $('[name="selectedData[]"]:checked').map(function(){
					return $(this).val();
				}).get();
				swal({
					title: '{{ __("Are you sure want to open this class?") }}',
					text: '',
					icon: 'warning',
					buttons: ['{{ __("Cancel") }}', true],
					dangerMode: true,
				})
				.then((willDo) => {
					if (willDo) {
						$.ajax({
							url : "{{ route('admin.class.open') }}",
							type: "POST",
							dataType: "JSON",
							data: {"selectedData" : selectedData, "_token" : "{{ csrf_token() }}"},
							success: function(data)
							{
								swal("{{ __('Success!') }}", "{{ __("Class has been opened.") }}", "success");
								reloadTable();
							},
							error: function (jqXHR, textStatus, errorThrown)
							{
								if (JSON.parse(jqXHR.responseText).status) {
									swal("{{ __('Failed!') }}", "{{ __("Data cannot been opened.") }}", "warning");
								} else {
									swal(JSON.parse(jqXHR.responseText).message, "", "error");
								}
							}
						});
					}
				});
			} else {
				swal("{{ __('Please select a data..') }}", "", "warning");
			}
		});

		$('[name="closeData"]').click(function(event) {
			if ($('[name="selectedData[]"]:checked').length > 0) {
				event.preventDefault();
				var selectedData = $('[name="selectedData[]"]:checked').map(function(){
					return $(this).val();
				}).get();
				swal({
			      	title: '{{ __("Are you sure want to close this class?") }}',
			      	text: '',
			      	icon: 'warning',
			      	buttons: ['{{ __("Cancel") }}', true],
			      	dangerMode: true,
			    })
			    .then((willDo) => {
			      	if (willDo) {
			      		$.ajax({
							url : "{{ route('admin.class.close') }}",
							type: "POST",
							dataType: "JSON",
							data: {"selectedData" : selectedData, "_token" : "{{ csrf_token() }}"},
							success: function(data)
							{
								swal("{{ __('Success!') }}", "{{ __("Data has be closed.") }}", "success");
								reloadTable();
							},
							error: function (jqXHR, textStatus, errorThrown)
							{
								if (JSON.parse(jqXHR.responseText).status) {
									swal("{{ __('Failed!') }}", "{{ __("Data cannot be closed.") }}", "warning");
								} else {
									swal(JSON.parse(jqXHR.responseText).message, "", "error");
								}
							}
						});
			      	}
    			});
			} else {
				swal("{{ __('Please select a data..') }}", "", "warning");
			}
		});

		$('[name="deleteData"]').click(function(event) {
			if ($('[name="selectedData[]"]:checked').length > 0) {
				event.preventDefault();
				var selectedData = $('[name="selectedData[]"]:checked').map(function(){
					return $(this).val();
				}).get();
				swal({
					title: '{{ __("Are you sure want to delete this data?") }}',
					text: '',
					icon: 'warning',
					buttons: ['{{ __("Cancel") }}', true],
					dangerMode: true,
				})
				.then((willDelete) => {
					if (willDelete) {
						$.ajax({
							url : "{{ route('admin.class.destroy') }}",
							type: "DELETE",
							dataType: "JSON",
							data: {"selectedData" : selectedData, "_token" : "{{ csrf_token() }}"},
							success: function(data)
							{
								reloadTable();
							},
							error: function (jqXHR, textStatus, errorThrown)
							{
								if (JSON.parse(jqXHR.responseText).status) {
									swal("{{ __('Failed!') }}", "{{ __("Data cannot be deleted.") }}", "warning");
								} else {
									swal(JSON.parse(jqXHR.responseText).message, "", "error");
								}
							}
						});
					}
				});
			} else {
				swal("{{ __('Please select a data..') }}", "", "warning");
			}
		});
	});

	function reloadTable() {
	    table.ajax.reload(null,false); //reload datatable ajax
	    $('[name="selectData"]').iCheck('uncheck');
	}

	function filter() {
		reloadTable();
		$('#filterModal').modal('hide');
	}
</script>

<!-- Modal -->
<div class="modal fade" id="filterModal" tabindex="-1" role="dialog" aria-labelledby="filterModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="filterModallLabel">{{ __('Filter') }}</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			{{ Form::open(['route' => 'admin.class.export', 'files' => true]) }}
				<div class="modal-body">
					<div class="container-fluid">
						<div class="row">
							{{ Form::bsSelect('col-sm-4', __('Level'), 'level', $levels, null, __('Select'), ['placeholder' => __('Select')]) }}
							{{ Form::bsSelect('col-sm-4', __('School'), 'school', $schools, null, __('Select'), ['placeholder' => __('Select')]) }}
							{{ Form::bsSelect('col-sm-4', __('Generation'), 'generation', $generations, null, __('Select'), ['placeholder' => __('Select')]) }}
							{{ Form::bsSelect('col-sm-4', __('School Year'), 'school_year', $schoolYears, null, __('Select'), ['placeholder' => __('Select')]) }}
							{{ Form::bsSelect('col-sm-4', __('Department'), 'department', $departments, null, __('Select'), ['placeholder' => __('Select')]) }}
							{{ Form::bsSelect('col-sm-4', __('SSP Status'), 'ssp_status', ['1' => __('Yes'), '0' => __('Not')], null, __('Select'), ['placeholder' => __('Select')], [__('This is only used for export.')]) }}
						</div>
					</div>
				</div>
				<div class="modal-footer bg-whitesmoke d-flex justify-content-center">
					{{ Form::submit(__('Export'), ['class' => 'btn btn-primary']) }}
					{{ Form::button(__('Filter'), ['class' => 'btn btn-primary', 'onclick' => 'filter()']) }}
					{{ Form::button(__('Cancel'), ['class' => 'btn btn-secondary', ' data-dismiss' => 'modal']) }}
				</div>
			{{ Form::close() }}
		</div>
	</div>
</div>
@endsection

resources/views/admin/class/show.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
	<div class="col-12">

		@if (session('alert-success'))
			<div class="alert alert-success alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-success') }}
				</div>
			</div>
		@endif

		@if (session('alert-danger'))
			<div class="alert alert-danger alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-danger') }}
				</div>
			</div>
		@endif

		<div class="card card-primary">

			{{ Form::open(['url' => '#', 'files' => true]) }}
				<div class="card-body">
					<div class="row">
						<div class="col-sm-6">
							<fieldset>
                                {{ Form::bsSelect(null, __('School'), 'school_id', $schools, $data->school_id, __('Select'), ['placeholder' => __('Select'), 'disabled' => '']) }}

                                {{ Form::bsSelect(null, __('Department'), 'department_id', $departments, $data->department_id, __('Select'), ['placeholder' => __('Select'), 'disabled' => '']) }}

                                {{ Form::bsText(null, __('Generation'), 'generation', $data->generation, __('Generation'), ['disabled' => '']) }}
                            </fieldset>
                        </div>
						<div class="col-sm-6">
							<fieldset>
                                {{ Form::bsText(null, __('School Year'), 'school_year', $data->school_year, __('School Year'), ['disabled' => '']) }}

                                {{ Form::bsText(null, __('Grade'), 'grade', $data->grade, __('Grade'), ['disabled' => '']) }}
                            </fieldset>
					</div>
				</div>
			{{ Form::close() }}

		</div>
	</div>
</div>
@endsection

@section('script')
<script>

</script>
@endsection