routes/web.php
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes(['register' => false]);

// School
Route::prefix('school')->name('school.')->group(function () {
	Route::get('register', 'SchoolController@create')->name('register');
	Route::post('/', 'SchoolController@store')->name('store');
});

// Default Guard (Web)
Route::middleware(['auth'])->group(function () {
	Route::middleware(['joined'])->group(function () {
		Route::middleware(['level:C|B|A'])->group(function () {
			// Class
			Route::prefix('class')->name('class.')->group(function () {
				Route::post('list', 'StudentClassController@list')->name('list');
				Route::post('close', 'StudentClassController@close')->name('close');
				// Route::post('export', 'StudentClassController@export')->name('export');
				// Route::delete('destroy', 'StudentClassController@destroy')->name('destroy');
				// Student
				Route::prefix('{studentClass}/student')->name('student.')->group(function () {
					Route::post('list', 'StudentController@list')->name('list');
					// Route::post('export', 'StudentController@export')->name('export');
					Route::post('import', 'StudentController@importExcel')->name('import');
					// Route::delete('destroy', 'StudentController@destroy')->name('destroy');
				});
				Route::resource('{studentClass}/student', 'StudentController', ['except' => [
					'destroy',
				]]);
			});
			Route::resource('class', 'StudentClassController', ['parameters' => [
				'class' => 'studentClass'
			], 'except' => [
				'destroy',
			]]);
		
			// Activity
			Route::prefix('activity')->name('activity.')->group(function () {
				Route::post('list', 'ActivityController@list')->name('list');
				// Route::delete('destroy', 'ActivityController@destroy')->name('destroy');
			});
			Route::resource('activity', 'ActivityController', ['except' => [
				'edit', 'update', 'destroy',
			]]);
		
			// Subsidy
			Route::prefix('subsidy')->name('subsidy.')->group(function () {
				Route::post('list', 'SubsidyController@list')->name('list');
				// Route::post('export', 'SubsidyController@export')->name('export');
				// Route::delete('destroy', 'SubsidyController@destroy')->name('destroy');
			});
			Route::resource('subsidy', 'SubsidyController', ['except' => [
				'destroy',
			]]);
		
			// Training
			Route::prefix('training')->name('training.')->group(function () {
				Route::post('list', 'TrainingController@list')->name('list');
				Route::post('preCreate', 'TrainingController@preCreate')->name('preCreate');
				// Route::post('export', 'TrainingController@export')->name('export');
				// Route::delete('destroy', 'TrainingController@destroy')->name('destroy');
			});
			Route::resource('training', 'TrainingController', ['except' => [
				'destroy',
			]]);
		
			// Exam
			Route::prefix('exam')->name('exam.')->group(function () {
				// Exam: readiness
				Route::prefix('readiness')->name('readiness.')->group(function () {
					Route::post('list', 'ExamReadinessController@list')->name('list');
					// Route::post('export', 'ExamReadinessController@export')->name('export');
					// Route::delete('destroy', 'ExamReadinessController@destroy')->name('destroy');
				});
				Route::resource('readiness', 'ExamReadinessController', ['parameters' => [
					'readiness' => 'examReadiness'
				], 'except' => [
					'destroy',
				]]);
			});
		
			// Payment
			Route::prefix('payment')->name('payment.')->group(function () {
				Route::post('list', 'PaymentController@list')->name('list');
				Route::get('{payment}/fill', 'PaymentController@fill')->name('fill');
				Route::put('{payment}/confirm', 'PaymentController@confirm')->name('confirm');
				// Route::post('export', 'PaymentController@export')->name('export');
				// Route::delete('destroy', 'PaymentController@destroy')->name('destroy');
			});
			Route::resource('payment', 'PaymentController', ['except' => [
				'destroy',
			]]);

			// Grant
			Route::prefix('grant')->name('grant.')->group(function () {
				Route::post('list', 'GrantController@list')->name('list');
				// Route::delete('destroy', 'GrantController@destroy')->name('destroy');
			});
			Route::resource('grant', 'GrantController', ['except' => [
				'edit', 'update', 'destroy',
			]]);
		});
	
		Route::middleware(['level:Dalam proses|A'])->group(function () {
			// Attendance
			Route::prefix('attendance')->name('attendance.')->group(function () {
				Route::post('list', 'AttendanceController@list')->name('list');
				Route::delete('destroy', 'AttendanceController@destroy')->name('destroy');
			});
			Route::resource('attendance', 'AttendanceController', ['except' => [
				'destroy',
			]]);
		});
	
		// Home
		Route::get('/', 'HomeController@index')->name('home');
		
		// School
		Route::prefix('school')->name('school.')->group(function () {
			Route::get('edit', 'SchoolController@edit')->name('edit');
			Route::put('update', 'SchoolController@update')->name('update');
		
			// School: document
			Route::prefix('document')->name('document.')->group(function () {
				Route::get('filter/{token?}', 'DocumentController@filter')->name('filter');
				Route::delete('destroy', 'DocumentController@destroy')->name('destroy');
			});
			Route::resource('document', 'DocumentController', ['only' => [
				'store',
			]]);
		
			// School: photo
			Route::prefix('photo')->name('photo.')->group(function () {
				Route::get('filter/{token?}', 'SchoolPhotoController@filter')->name('filter');
				Route::delete('destroy', 'SchoolPhotoController@destroy')->name('destroy');
			});
			Route::resource('photo', 'SchoolPhotoController', ['only' => [
				'store',
			]]);
		});
		Route::resource('school', 'SchoolController', ['only' => [
			'index'
		]]);
		
		// Document
		Route::resource('document', 'DocumentController', ['except' => [
			'destroy',
		]]);
		
		// Teacher
		Route::prefix('teacher')->name('teacher.')->group(function () {
			Route::post('list', 'TeacherController@list')->name('list');
			Route::post('export', 'TeacherController@export')->name('export');
			Route::delete('destroy', 'TeacherController@destroy')->name('destroy');
		});
		Route::resource('teacher', 'TeacherController', ['except' => [
			'destroy',
		]]);
		
		// Account
		Route::prefix('account')->name('account.')->group(function () {
			Route::put('update', 'AccountController@update')->name('update');
		});
		Route::resource('account', 'AccountController', ['parameters' => [
			'account' => 'user'
		], 'only' => [
			'index',
		]]);
	});

	// School
	Route::prefix('school')->name('school.')->group(function () {
		Route::get('set', 'SchoolController@set')->name('set');
		Route::post('set', 'SchoolController@setStore')->name('set.store');
	});
});

/**
 * Admin Guard
 */
Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware(['auth:admin'])->group(function () {
	// Home
    Route::get('/', 'HomeController@index')->name('home');

	// Auth
	/**
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
	Route::post('logout', 'Auth\LoginController@logout')->name('logout');
	**/

    // School
    Route::prefix('school')->name('school.')->group(function () {
    	Route::post('list', 'SchoolController@list')->name('list');
    	Route::post('export', 'SchoolController@export')->name('export');
		Route::delete('destroy', 'SchoolController@destroy')->name('destroy');
		Route::get('bin', 'SchoolController@bin')->name('bin');
		Route::post('binList', 'SchoolController@list')->name('binList');
		Route::post('restore', 'SchoolController@restore')->name('restore');
		Route::delete('destroyPermanently', 'SchoolController@destroyPermanently')->name('destroyPermanently');
		
		// School: document
		Route::prefix('document')->name('document.')->group(function () {
			Route::get('{school}/filter/{token?}', 'DocumentController@filter')->name('filter');
			Route::delete('destroy', 'DocumentController@destroy')->name('destroy');
		});
		Route::resource('{school}/document', 'DocumentController', ['only' => [
			'store',
		]]);

		// School: photo
		Route::prefix('photo')->name('photo.')->group(function () {
			Route::get('{school}/filter/{token?}', 'SchoolPhotoController@filter')->name('filter');
			Route::delete('destroy', 'SchoolPhotoController@destroy')->name('destroy');
		});
		Route::resource('{school}/photo', 'SchoolPhotoController', ['only' => [
			'store',
		]]);

    	// School: comment
    	Route::prefix('comment')->name('comment.')->group(function () {
	    	Route::post('{school}', 'SchoolCommentController@store')->name('store');
	    });
    	/**
    	Route::resource('comment', 'SchoolCommentController', ['only' => [
			'index',
		]]);
		**/
    });
    Route::resource('school', 'SchoolController', ['except' => [
		'destroy',
	]]);

	// Teacher
	Route::prefix('teacher')->name('teacher.')->group(function () {
		Route::post('list', 'TeacherController@list')->name('list');
    	Route::post('export', 'TeacherController@export')->name('export');
		Route::delete('destroy', 'TeacherController@destroy')->name('destroy');
	});
	Route::resource('teacher', 'TeacherController', ['except' => [
		'destroy',
	]]);

	// Class
	Route::prefix('class')->name('class.')->group(function () {
    	Route::post('list', 'StudentClassController@list')->name('list');
    	Route::post('export', 'StudentClassController@export')->name('export');
		Route::delete('destroy', 'StudentClassController@destroy')->name('destroy');
		Route::post('close', 'StudentClassController@close')->name('close');
		Route::post('open', 'StudentClassController@open')->name('open');
		// Student
		Route::prefix('{studentClass}/student')->name('student.')->group(function () {
			Route::post('list', 'StudentController@list')->name('list');
			Route::post('export', 'StudentController@export')->name('export');
			Route::post('import', 'StudentController@importExcel')->name('import');

app/Payment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Datakrama\Eloquid\Traits\Uuids;

class Payment extends Model
{
    use Uuids, SoftDeletes;
    
    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['notif'];

    /**
     * Get the school that owns the payment.
     */
    public function school()
    {
        return $this->belongsTo('App\School');
    }

     /**
     * Get the installment for the payment.
     */
    public function installments()
    {
        return $this->hasMany('App\PaymentInstallment');
    }

    /**
     * Get the payment status for the payment.
     */
    public function paymentStatuses()
    {
        return $this->hasMany('App\PaymentStatus');
    }

    /**
     * Get the latest payment status for the payment.
     */
    public function paymentStatus()
    {
        return $this->hasOne('App\PaymentStatus')->orderBy('created_at', 'desc')->limit(1);
    }

    /**
     * The status that belong to the payment.
     */
    public function statuses()
    {
        return $this->belongsToMany('App\Status', 'payment_statuses')->using('App\PaymentStatus')->withTimestamps();
    }

    /**
     * Get the subsidy payment for the payment.
     */
    public function subsidyPayment()
    {
        return $this->hasOne('App\SubsidyPayment');
    }

    /**
     * The subsidy that belong to the payment.
     */
    public function subsidy()
    {
        return $this->belongsToMany('App\Subsidy', 'subsidy_payments')->using('App\SubsidyPayment')->withTimestamps();
    }

    /**
     * Get the training payment for the payment.
     */
    public function trainingPayment()
    {
        return $this->hasOne('App\TrainingPayment');
    }

    /**
     * The training that belong to the payment.
     */
    public function training()
    {
        return $this->belongsToMany('App\Training', 'training_payments')->using('App\TrainingPayment')->withTimestamps();
    }

    /**
     * Main query for listing
     * 
     * @param  \Illuminate\Http\Request  $request
     */
    public static function get(Request $request)
    {
        return DB::table('payments')
            ->join('payment_statuses', 'payment_statuses.id', '=', DB::raw('(SELECT id FROM payment_statuses WHERE payment_statuses.payment_id = payments.id ORDER BY created_at DESC LIMIT 1)'))
            ->join('statuses', 'payment_statuses.status_id', '=', 'statuses.id')
            ->join('activity_logs', 'payment_statuses.log_id', '=', 'activity_logs.id')
            ->leftJoin('users', 'activity_logs.user_id', '=', 'users.id')
            ->leftJoin('staffs', 'activity_logs.staff_id', '=', 'staffs.id')
            ->join('schools', 'payments.school_id', '=', 'schools.id')
            ->leftJoin('provinces', 'schools.province', '=', 'provinces.name')
            ->leftJoin('subsidy_payments', 'payments.id', '=', 'subsidy_payments.payment_id')
            ->leftJoin('subsidies', 'subsidy_payments.subsidy_id', '=', 'subsidies.id')
            ->leftJoin('training_payments', 'payments.id', '=', 'training_payments.payment_id')
            ->leftJoin('trainings', 'training_payments.training_id', '=', 'trainings.id')
            ->when(auth()->guard('web')->check(), function ($query) use ($request) {
                $query->where('schools.id', auth()->user()->school->id);
                $query->where('statuses.name', '!=', 'Published');
            })->when( ! empty($request->school), function ($query) use ($request) {
                $query->where('schools.id', $request->school);
            })->when( ! empty($request->type), function ($query) use ($request) {
                $query->where('payments.type', $request->type);
            })->when( ! empty($request->status), function ($query) use ($request) {
                $query->where('statuses.id', $request->status);
            })->when($request->is('admin/payment/list')||$request->is('admin/payment/export'), function ($query) {
                $query->whereNull('payments.deleted_at');
            })->when($request->is('admin/payment/binList'), function ($query) {
                $query->whereNotNull('payments.deleted_at');
            })
            ->whereNull('schools.deleted_at')
            ->where('statuses.name', '!=', 'Published');
    }

    /**
     * Show main list for datatable
     * 
     * @param  \Illuminate\Http\Request  $request
     */
    public static function list(Request $request)
    {
        return self::get($request)->select('payments.*', 'schools.name as school', 'schools.school_email', 'provinces.abbreviation', 'subsidies.id as subsidy_id', 'subsidies.type as subsidy_type', 'trainings.id as training_id', 'trainings.type as training_type', 'statuses.name as status', 'payment_statuses.created_at as statused_at', DB::raw('(CASE WHEN staffs.name IS NULL THEN users.name WHEN users.name IS NULL THEN staffs.name ELSE staffs.name END) AS status_by'));
    }
}

resources/views/payment/create.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
	<div class="col-12">

		@if (session('alert-success'))
			<div class="alert alert-success alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-success') }}
				</div>
			</div>
		@endif

		@if (session('alert-danger'))
			<div class="alert alert-danger alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-danger') }}
				</div>
			</div>
		@endif

		<div class="card card-primary">

			{{ Form::open(['route' => 'payment.store', 'files' => true]) }}
				<div class="card-body">
					<div class="row">
                        <div class="col-sm-6">
                            <fieldset>
                                {{ Form::bsSelect(null, __('Type'), 'type', $types, old('type'), __('Select'), ['placeholder' => __('Select'), 'required' => '']) }}

								{{ Form::bsText((old('type')!='Biaya Pengiriman Mikrotik'?'d-block':'d-none'), __('Invoice'), 'invoice', old('invoice'), __('Invoice'), ['required' => '']) }}

								{{ Form::bsText(null, __('Payment Date'), 'date', old('date'), __('DD-MM-YYYY'), ['required' => '']) }}
                            </fieldset>
                            <fieldset>
								<legend>{{ __('Return Account Information') }}</legend>
								{{ Form::bsSelect(null, __('Bank Name'), 'receiver_bank_name', $bankSenders, old('receiver_bank_name'), __('Select'), ['placeholder' => __('Select'), 'required' => '']) }}

								{{ Form::bsText(null, __('Bank Account Number'), 'receiver_bill_number', old('receiver_bill_number'), __('Bank Account Number'), ['required' => ''], [__('No punctuation or comma or strip. 10 digits minimum.')]) }}

								{{ Form::bsText(null, __('On Behalf of'), 'receiver_on_behalf_of', old('receiver_on_behalf_of'), __('On Behalf of'), ['required' => ''], [__('As per the name on the account')]) }}

								{{ Form::bsFile(null, __('Bank Account Book'), 'bank_account_book', null, [], [__('For the return process to run without problems, the photo must show the account number.'), __('File with PDF/JPG/PNG format up to 5MB.')]) }}
							</fieldset>
                        </div>
                        <div class="col-sm-6">
							<fieldset>
								{{ Form::bsCurrency(null, __('Payment Ammount'), 'total', old('total'), __('Payment Ammount'), ['required' => '']) }}
								
								{{ Form::bsSelect(null, __('Method'), 'method', $methods, old('method'), __('Select'), ['placeholder' => __('Select'), 'required' => '']) }}

								{{ Form::bsSelect((old('method')=='ATM'?'d-block':'d-none'), __('Bank Sender'), 'bank_sender', $bankSenders, old('bank_sender'), __('Select'), ['placeholder' => __('Select')]) }}

								{{ Form::bsFile(null, __('Payment Receipt'), 'payment_receipt', old('payment_receipt'), ['required' => ''], [__('File with PDF/JPG/PNG format up to 5MB.')]) }}
							</fieldset>
                        </div>
					</div>
				</div>
				<div class="card-footer bg-whitesmoke text-center">
					{{ Form::submit(__('Save'), ['class' => 'btn btn-primary']) }}
					{{ link_to(url()->previous(),__('Cancel'), ['class' => 'btn btn-danger']) }}
				</div>
			{{ Form::close() }}

		</div>
	</div>
</div>
@endsection

@section('script')
<script>
	$(document).ready(function () {
		$('[name="date"]').keypress(function(e) {
            e.preventDefault();
        }).daterangepicker({
        	locale: {format: 'DD-MM-YYYY'},
        	singleDatePicker: true,
      	});

        $('select[name="type"]').change(function () {
			if ($(this).val() == 'Biaya Pengiriman Mikrotik') {
				$('input[name="invoice"]').prop('required', false).val('');
				$('input[name="invoice"]').closest('.form-group').removeClass('d-block').addClass('d-none');
	    	} else {
				$('input[name="invoice"]').prop('required', true).val('');
				$('input[name="invoice"]').closest('.form-group').removeClass('d-none').addClass('d-block');
			}
		});

		$('select[name="method"]').change(function () {
			if ($(this).val() == 'ATM') {
				$('select[name="bank_sender"]').prop('required', true);
				$('select[name="bank_sender"]').val(null).change();
				$('select[name="bank_sender"]').closest('.form-group').removeClass('d-none').addClass('d-block');
			} else {
				$('select[name="bank_sender"]').prop('required', false);
				$('select[name="bank_sender"]').val(null).change();
				$('select[name="bank_sender"]').closest('.form-group').removeClass('d-block').addClass('d-none');
			}
		});
	});
</script>
@endsection

resources/views/payment/index.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
	<div class="col-12">

		@if (session('alert-success'))
			<div class="alert alert-success alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-success') }}
				</div>
			</div>
		@endif

		@if (session('alert-danger'))
			<div class="alert alert-danger alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-danger') }}
				</div>
			</div>
		@endif

		@if ($subsidyPayments->count()+$trainingPayments->count() > 0)
			<div class="card card-warning">
				<div class="card-header">
					{{ __('Bill') }}
				</div>
				<ul class="list-group list-group-flush">
					@foreach ($subsidyPayments as $subsidyPayment)
						<li class="list-group-item d-flex justify-content-between align-items-center">
							{{ __('Subsidy') }} {{ $subsidyPayment->subsidy[0]->type }} &middot; {{ __($subsidyPayment->subsidy[0]->subsidyStatus->status->name) }} {{ __('at') }} {{ date('d-m-Y', strtotime($subsidyPayment->subsidy[0]->subsidyStatus->created_at)) }}
							{{ link_to_route('payment.fill',__('Fill'), ['payment' => $subsidyPayment->id], ['class' => 'badge badge-primary badge-pill']) }}
						</li>
					@endforeach
					@foreach ($trainingPayments as $trainingPayment)
						<li class="list-group-item d-flex justify-content-between align-items-center">
							{{ __('Training') }} {{ $trainingPayment->training[0]->type }} &middot; {{ __('Expired') }} {{ __('at') }} {{ date('d-m-Y H:i:s', strtotime($trainingPayment->training[0]->trainingStatus->created_at . '+3 hours')) }}
							{{ link_to_route('payment.fill',__('Fill'), ['payment' => $trainingPayment->id], ['class' => 'badge badge-primary badge-pill']) }}
						</li>
					@endforeach
				</ul>
			</div>
		@endif

		<div class="card card-primary">
			<div class="card-header">
				<a href="{{ route('payment.create') }}" class="btn btn-icon btn-success" title="{{ __('Create') }}"><i class="fa fa-plus"></i></a>
				<button class="btn btn-icon btn-secondary" title="{{ __('Filter') }}" data-toggle="modal" data-target="#filterModal"><i class="fa fa-filter"></i></button>
            	<button class="btn btn-icon btn-secondary" onclick="reloadTable()" title="{{ __('Refresh') }}"><i class="fa fa-sync"></i></i></button>
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table table-sm table-striped" id="table4data">
						<thead>
							<tr>
								<th>
									<div class="checkbox icheck"><label><input type="checkbox" name="selectData"></label></div>
								</th>
								<th>{{ __('Created At') }}</th>
								<th>{{ __('School') }}</th>
								<th>{{ __('Type') }}</th>
								<th>{{ __('Payment Receipt') }}</th>
                                <th>{{ __('Bank Account Book') }}</th>
								<th>{{ __('NPWP') }}</th>
								<th>{{ __('Status') }}</th>
								<th>{{ __('Action') }}</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
			<div class="card-footer bg-whitesmoke">
			</div>
		</div>

	</div>
</div>
@endsection

@section('script')
<script>
	var table;
	$(document).ready(function() {
		table = $('#table4data').DataTable({
			processing: true,
			serverSide: true,
			"ajax": {
				"url": "{{ route('payment.list') }}",
				"type": "POST",
				"data": function (d) {
		          d._token = "{{ csrf_token() }}";
		          d.type = $('select[name="type"]').val();
		          d.status = $('select[name="status"]').val();
		        }
			},
			columns: [
				{ data: 'DT_RowIndex', name: 'DT_RowIndex', 'searchable': false },
				{ data: 'created_at', name: 'created_at' },
                { data: 'school', name: 'schools.name' },
				{ data: 'type', name: 'payments.type' },
				{ data: 'payment_receipt', name: 'payments.payment_receipt' },
				{ data: 'bank_account_book', name: 'payments.bank_account_book' },
				{ data: 'npwp_number', name: 'payments.npwp_number' },
				{ data: 'status', name: 'statuses.name' },
				{ data: 'action', name: 'action', 'searchable': false },
			],
			"order": [[ 1, 'desc' ]],
			"columnDefs": [
			{   
          		"targets": [ 0, -1 ], //last column
          		"orderable": false, //set not orderable
      		},
      		],
      		"drawCallback": function(settings) {
      			$('input[name="selectData"], input[name="selectedData[]"]').iCheck({
      				checkboxClass: 'icheckbox_flat-green',
      				radioClass: 'iradio_flat-green',
      				increaseArea: '20%' /* optional */
      			});
      			$('[name="selectData"]').on('ifChecked', function(event){
      				$('[name="selectedData[]"]').iCheck('check');
      			}).on('ifUnchecked', function(event){
      				$('[name="selectedData[]"]').iCheck('uncheck');
      			});
      		},
  		});
		
		@if (session('alert-success'))
			swal("", "{{ session('alert-success') }}", "success");
		@endif
	});

	function reloadTable() {
	    table.ajax.reload(null,false); //reload datatable ajax
	    $('[name="selectData"]').iCheck('uncheck');
	}

	function filter() {
		reloadTable();
		$('#filterModal').modal('hide');
	}
</script>

<!-- Modal -->
<div class="modal fade" id="filterModal" tabindex="-1" role="dialog" aria-labelledby="filterModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="filterModallLabel">{{ __('Filter') }}</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			{{ Form::open(['url' => '#', 'files' => true]) }}
				<div class="modal-body">
					<div class="container-fluid">
						<div class="row">
							{{ Form::bsSelect('col-sm-4', __('Type'), 'type', $types, null, __('Select'), ['placeholder' => __('Select')]) }}
							{{ Form::bsSelect('col-sm-4', __('Status'), 'status', $statuses, null, __('Select'), ['placeholder' => __('Select')]) }}
						</div>
					</div>
				</div>
				<div class="modal-footer bg-whitesmoke d-flex justify-content-center">
					{{ Form::button(__('Filter'), ['class' => 'btn btn-primary', 'onclick' => 'filter()']) }}
					{{ Form::button(__('Cancel'), ['class' => 'btn btn-secondary', ' data-dismiss' => 'modal']) }}
				</div>
			{{ Form::close() }}
		</div>
	</div>
</div>
@endsection