routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes(['register' => false]);

// School
Route::prefix('school')->name('school.')->group(function () {
	Route::get('register', 'SchoolController@create')->name('register');
	Route::post('/', 'SchoolController@store')->name('store');
});

// Default Guard (Web)
Route::middleware(['auth'])->group(function () {
	Route::middleware(['joined'])->group(function () {
		Route::middleware(['level:C|B|A'])->group(function () {
			// Class
			Route::prefix('class')->name('class.')->group(function () {
				Route::post('list', 'StudentClassController@list')->name('list');
				Route::post('close', 'StudentClassController@close')->name('close');
				// Route::post('export', 'StudentClassController@export')->name('export');
				// Route::delete('destroy', 'StudentClassController@destroy')->name('destroy');
				// Student
				Route::prefix('{studentClass}/student')->name('student.')->group(function () {
					Route::post('list', 'StudentController@list')->name('list');
					// Route::post('export', 'StudentController@export')->name('export');
					Route::post('import', 'StudentController@importExcel')->name('import');
					// Route::delete('destroy', 'StudentController@destroy')->name('destroy');
				});
				Route::resource('{studentClass}/student', 'StudentController', ['except' => [
					'destroy',
				]]);
			});
			Route::resource('class', 'StudentClassController', ['parameters' => [
				'class' => 'studentClass'
			], 'except' => [
				'destroy',
			]]);
		
			// Activity
			Route::prefix('activity')->name('activity.')->group(function () {
				Route::post('list', 'ActivityController@list')->name('list');
				// Route::delete('destroy', 'ActivityController@destroy')->name('destroy');
			});
			Route::resource('activity', 'ActivityController', ['except' => [
				'edit', 'update', 'destroy',
			]]);
		
			// Subsidy
			Route::prefix('subsidy')->name('subsidy.')->group(function () {
				Route::post('list', 'SubsidyController@list')->name('list');
				// Route::post('export', 'SubsidyController@export')->name('export');
				// Route::delete('destroy', 'SubsidyController@destroy')->name('destroy');
			});
			Route::resource('subsidy', 'SubsidyController', ['except' => [
				'destroy',
			]]);
		
			// Training
			Route::prefix('training')->name('training.')->group(function () {
				Route::post('list', 'TrainingController@list')->name('list');
				Route::post('preCreate', 'TrainingController@preCreate')->name('preCreate');
				// Route::post('export', 'TrainingController@export')->name('export');
				// Route::delete('destroy', 'TrainingController@destroy')->name('destroy');
			});
			Route::resource('training', 'TrainingController', ['except' => [
				'destroy',
			]]);
		
			// Exam
			Route::prefix('exam')->name('exam.')->group(function () {
				// Exam: readiness
				Route::prefix('readiness')->name('readiness.')->group(function () {
					Route::post('list', 'ExamReadinessController@list')->name('list');
					// Route::post('export', 'ExamReadinessController@export')->name('export');
					// Route::delete('destroy', 'ExamReadinessController@destroy')->name('destroy');
				});
				Route::resource('readiness', 'ExamReadinessController', ['parameters' => [
					'readiness' => 'examReadiness'
				], 'except' => [
					'destroy',
				]]);
			});
		
			// Payment
			Route::prefix('payment')->name('payment.')->group(function () {
				Route::post('list', 'PaymentController@list')->name('list');
				Route::get('{payment}/fill', 'PaymentController@fill')->name('fill');
				Route::put('{payment}/confirm', 'PaymentController@confirm')->name('confirm');
				// Route::post('export', 'PaymentController@export')->name('export');
				// Route::delete('destroy', 'PaymentController@destroy')->name('destroy');
			});
			Route::resource('payment', 'PaymentController', ['except' => [
				'destroy',
			]]);

			// Grant
			Route::prefix('grant')->name('grant.')->group(function () {
				Route::post('list', 'GrantController@list')->name('list');
				// Route::delete('destroy', 'GrantController@destroy')->name('destroy');
			});
			Route::resource('grant', 'GrantController', ['except' => [
				'edit', 'update', 'destroy',
			]]);
		});
	
		Route::middleware(['level:Dalam proses|A'])->group(function () {
			// Attendance
			Route::prefix('attendance')->name('attendance.')->group(function () {
				Route::post('list', 'AttendanceController@list')->name('list');
				Route::delete('destroy', 'AttendanceController@destroy')->name('destroy');
			});
			Route::resource('attendance', 'AttendanceController', ['except' => [
				'destroy',
			]]);
		});
	
		// Home
		Route::get('/', 'HomeController@index')->name('home');
		
		// School
		Route::prefix('school')->name('school.')->group(function () {
			Route::get('edit', 'SchoolController@edit')->name('edit');
			Route::put('update', 'SchoolController@update')->name('update');
		
			// School: document
			Route::prefix('document')->name('document.')->group(function () {
				Route::get('filter/{token?}', 'DocumentController@filter')->name('filter');
				Route::delete('destroy', 'DocumentController@destroy')->name('destroy');
			});
			Route::resource('document', 'DocumentController', ['only' => [
				'store',
			]]);
		
			// School: photo
			Route::prefix('photo')->name('photo.')->group(function () {
				Route::get('filter/{token?}', 'SchoolPhotoController@filter')->name('filter');
				Route::delete('destroy', 'SchoolPhotoController@destroy')->name('destroy');
			});
			Route::resource('photo', 'SchoolPhotoController', ['only' => [
				'store',
			]]);
		});
		Route::resource('school', 'SchoolController', ['only' => [
			'index'
		]]);
		
		// Document
		Route::resource('document', 'DocumentController', ['except' => [
			'destroy',
		]]);
		
		// Teacher
		Route::prefix('teacher')->name('teacher.')->group(function () {
			Route::post('list', 'TeacherController@list')->name('list');
			Route::post('export', 'TeacherController@export')->name('export');
			Route::delete('destroy', 'TeacherController@destroy')->name('destroy');
		});
		Route::resource('teacher', 'TeacherController', ['except' => [
			'destroy',
		]]);
		
		// Account
		Route::prefix('account')->name('account.')->group(function () {
			Route::put('update', 'AccountController@update')->name('update');
		});
		Route::resource('account', 'AccountController', ['parameters' => [
			'account' => 'user'
		], 'only' => [
			'index',
		]]);
	});

	// School
	Route::prefix('school')->name('school.')->group(function () {
		Route::get('set', 'SchoolController@set')->name('set');
		Route::post('set', 'SchoolController@setStore')->name('set.store');
	});
});

/**
 * Admin Guard
 */
Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware(['auth:admin'])->group(function () {
	// Home
    Route::get('/', 'HomeController@index')->name('home');

	// Auth
	/**
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
	Route::post('logout', 'Auth\LoginController@logout')->name('logout');
	**/

    // School
    Route::prefix('school')->name('school.')->group(function () {
    	Route::post('list', 'SchoolController@list')->name('list');
    	Route::post('export', 'SchoolController@export')->name('export');
		Route::delete('destroy', 'SchoolController@destroy')->name('destroy');
		Route::get('bin', 'SchoolController@bin')->name('bin');
		Route::post('binList', 'SchoolController@list')->name('binList');
		Route::post('restore', 'SchoolController@restore')->name('restore');
		Route::delete('destroyPermanently', 'SchoolController@destroyPermanently')->name('destroyPermanently');
		
		// School: document
		Route::prefix('document')->name('document.')->group(function () {
			Route::get('{school}/filter/{token?}', 'DocumentController@filter')->name('filter');
			Route::delete('destroy', 'DocumentController@destroy')->name('destroy');
		});
		Route::resource('{school}/document', 'DocumentController', ['only' => [
			'store',
		]]);

		// School: photo
		Route::prefix('photo')->name('photo.')->group(function () {
			Route::get('{school}/filter/{token?}', 'SchoolPhotoController@filter')->name('filter');
			Route::delete('destroy', 'SchoolPhotoController@destroy')->name('destroy');
		});
		Route::resource('{school}/photo', 'SchoolPhotoController', ['only' => [
			'store',
		]]);

    	// School: comment
    	Route::prefix('comment')->name('comment.')->group(function () {
	    	Route::post('{school}', 'SchoolCommentController@store')->name('store');
	    });
    	/**
    	Route::resource('comment', 'SchoolCommentController', ['only' => [
			'index',
		]]);
		**/
    });
    Route::resource('school', 'SchoolController', ['except' => [
		'destroy',
	]]);

	// Teacher
	Route::prefix('teacher')->name('teacher.')->group(function () {
		Route::post('list', 'TeacherController@list')->name('list');
    	Route::post('export', 'TeacherController@export')->name('export');
		Route::delete('destroy', 'TeacherController@destroy')->name('destroy');
	});
	Route::resource('teacher', 'TeacherController', ['except' => [
		'destroy',
	]]);

	// Class
	Route::prefix('class')->name('class.')->group(function () {
    	Route::post('list', 'StudentClassController@list')->name('list');
    	Route::post('export', 'StudentClassController@export')->name('export');
		Route::delete('destroy', 'StudentClassController@destroy')->name('destroy');
		Route::post('close', 'StudentClassController@close')->name('close');
		Route::post('open', 'StudentClassController@open')->name('open');
		// Student

resources/views/admin/school/bin.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
	<div class="col-12">

		@if (session('alert-success'))
			<div class="alert alert-success alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-success') }}
				</div>
			</div>
		@endif

		@if (session('alert-danger'))
			<div class="alert alert-danger alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-danger') }}
				</div>
			</div>
		@endif

		<div class="card card-primary">
			<div class="card-header">
            	<button class="btn btn-icon btn-secondary" onclick="reloadTable()" title="{{ __('Refresh') }}"><i class="fa fa-sync"></i></i></button>
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table table-sm table-striped" id="table4data">
						<thead>
							<tr>
								<th>
									<div class="checkbox icheck"><label><input type="checkbox" name="selectData"></label></div>
								</th>
								<th>{{ __('Created At') }}</th>
								<th>{{ __('Type') }}</th>
								<th>{{ __('Level') }}</th>
								<th>{{ __('Name') }}</th>
								<th>{{ __('Province') }}</th>
								<th>{{ __('Regency') }}</th>
								<th>{{ __('Headmaster') }}</th>
								<th>{{ __('PIC') }}</th>
								<th>{{ __('Status') }}</th>
								<th>{{ __('Code') }}</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
			<div class="card-footer bg-whitesmoke">
				@if (auth()->guard('admin')->user()->can('restore schools'))
					<button class="btn btn-warning btn-sm" name="restoreData" title="{{ __('Restore') }}">{{ __('Restore') }}</button>
				@endif
				@if (auth()->guard('admin')->user()->can('force_delete schools'))
					<button class="btn btn-danger btn-sm" name="deleteData" title="{{ __('Delete Permanently') }}">{{ __('Delete Permanently') }}</button>
				@endif
			</div>
		</div>

	</div>
</div>
@endsection

@section('script')
<script>
	var table;
	$(document).ready(function() {
		table = $('#table4data').DataTable({
			processing: true,
			serverSide: true,
			"ajax": {
				"url": "{{ route('admin.school.binList') }}",
				"type": "POST",
				"data": function (d) {
		          d._token = "{{ csrf_token() }}";
		        }
			},
			columns: [
				{ data: 'DT_RowIndex', name: 'DT_RowIndex', 'searchable': false },
				{ data: 'created_at', name: 'created_at' },
				{ data: 'type', name: 'schools.type' },
				{ data: 'level_name', name: 'school_levels.name' },
				{ data: 'name', name: 'schools.name' },
				{ data: 'province', name: 'schools.province' },
				{ data: 'regency', name: 'schools.regency' },
				{ data: 'headmaster_name', name: 'schools.headmaster_name' },
				{ data: 'pic_name', name: 'pics.name' },
				{ data: 'status_name', name: 'school_statuses.name' },
				{ data: 'code', name: 'schools.code' },
			],
			"columnDefs": [
			{   
          		"targets": [ 0, -1 ], //last column
          		"orderable": false, //set not orderable
      		},
      		],
      		"drawCallback": function(settings) {
      			$('input[name="selectData"], input[name="selectedData[]"]').iCheck({
      				checkboxClass: 'icheckbox_flat-green',
      				radioClass: 'iradio_flat-green',
      				increaseArea: '20%' /* optional */
      			});
      			$('[name="selectData"]').on('ifChecked', function(event){
      				$('[name="selectedData[]"]').iCheck('check');
      			}).on('ifUnchecked', function(event){
      				$('[name="selectedData[]"]').iCheck('uncheck');
      			});
      		},
  		});

		$('[name="restoreData"]').click(function(event) {
			if ($('[name="selectedData[]"]:checked').length > 0) {
				event.preventDefault();
				var selectedData = $('[name="selectedData[]"]:checked').map(function(){
					return $(this).val();
				}).get();
				swal({
			      	title: '{{ __("Are you sure want to restore this data?") }}',
			      	text: '',
			      	icon: 'warning',
			      	buttons: ['{{ __("Cancel") }}', true],
			      	dangerMode: true,
			    })
			    .then((willRestore) => {
			      	if (willRestore) {
			      		$.ajax({
							url : "{{ route('admin.school.restore') }}",
							type: "POST",
							dataType: "JSON",
							data: {"selectedData" : selectedData, "_token" : "{{ csrf_token() }}"},
							success: function(data)
							{
								reloadTable();
							},
							error: function (jqXHR, textStatus, errorThrown)
							{
								if (JSON.parse(jqXHR.responseText).status) {
									swal("{{ __('Failed!') }}", '{{ __("Data cannot be restored.") }}', "warning");
								} else {
									swal(JSON.parse(jqXHR.responseText).message, "", "error");
								}
							}
						});
			      	}
    			});
			} else {
				swal("{{ __('Please select a data..') }}", "", "warning");
			}
		});

		$('[name="deleteData"]').click(function(event) {
			if ($('[name="selectedData[]"]:checked').length > 0) {
				event.preventDefault();
				var selectedData = $('[name="selectedData[]"]:checked').map(function(){
					return $(this).val();
				}).get();
				swal({
			      	title: '{{ __("Are you sure want to delete permanently this data?") }}',
			      	text: '{{ __("After this, data cannot be restored.") }}',
			      	icon: 'warning',
			      	buttons: ['{{ __("Cancel") }}', true],
			      	dangerMode: true,
			    })
			    .then((willDelete) => {
			      	if (willDelete) {
			      		$.ajax({
							url : "{{ route('admin.school.destroyPermanently') }}",
							type: "DELETE",
							dataType: "JSON",
							data: {"selectedData" : selectedData, "_token" : "{{ csrf_token() }}"},
							success: function(data)
							{
								reloadTable();
							},
							error: function (jqXHR, textStatus, errorThrown)
							{
								if (JSON.parse(jqXHR.responseText).status) {
									swal("{{ __('Failed!') }}", '{{ __("Data cannot be deleted.") }}', "warning");
								} else {
									swal(JSON.parse(jqXHR.responseText).message, "", "error");
								}
							}
						});
			      	}
    			});
			} else {
				swal("{{ __('Please select a data..') }}", "", "warning");
			}
		});
	});

	function reloadTable() {
	    table.ajax.reload(null,false); //reload datatable ajax
	    $('[name="selectData"]').iCheck('uncheck');
	}
</script>
@endsection

resources/views/admin/school/index.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
	<div class="col-12">

		@if (session('alert-success'))
			<div class="alert alert-success alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-success') }}
				</div>
			</div>
		@endif

		@if (session('alert-danger'))
			<div class="alert alert-danger alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-danger') }}
				</div>
			</div>
		@endif

		<div class="card card-primary">
			<div class="card-header">
				@if(auth()->guard('admin')->user()->can('create schools'))
					<a href="{{ route('admin.school.create') }}" class="btn btn-icon btn-success" title="{{ __('Create') }}"><i class="fa fa-plus"></i></a>
				@endif
				<button class="btn btn-icon btn-secondary" title="{{ __('Filter') }}" data-toggle="modal" data-target="#filterModal"><i class="fa fa-filter"></i></button>
            	<button class="btn btn-icon btn-secondary" onclick="reloadTable()" title="{{ __('Refresh') }}"><i class="fa fa-sync"></i></i></button>
				@if(auth()->guard('admin')->user()->can('bin schools'))
					<a href="{{ route('admin.school.bin') }}" class="btn btn-icon btn-danger" title="{{ __('Bin') }}"><i class="fas fa-trash"></i></a>
				@endif
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table table-sm table-striped" id="table4data">
						<thead>
							<tr>
								<th>
									<div class="checkbox icheck"><label><input type="checkbox" name="selectData"></label></div>
								</th>
								<th>{{ __('Created At') }}</th>
								<th>{{ __('Type') }}</th>
								<th>{{ __('Level') }}</th>
								<th>{{ __('Name') }}</th>
								<th>{{ __('Province') }}</th>
								<th>{{ __('Regency') }}</th>
								<th>{{ __('Headmaster') }}</th>
								<th>{{ __('PIC') }}</th>
								<th>{{ __('Status') }}</th>
								<th>{{ __('Code') }}</th>
								<th>{{ __('Action') }}</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
			<div class="card-footer bg-whitesmoke">
				@if (auth()->guard('admin')->user()->can('delete schools'))
					<button class="btn btn-danger btn-sm" name="deleteData" title="{{ __('Delete') }}">{{ __('Delete') }}</button>
				@endif
			</div>
		</div>

	</div>
</div>
@endsection

@section('script')
<script>
	var table;
	$(document).ready(function() {
		table = $('#table4data').DataTable({
			processing: true,
			serverSide: true,
			"ajax": {
				"url": "{{ route('admin.school.list') }}",
				"type": "POST",
				"data": function (d) {
		          d._token = "{{ csrf_token() }}";
		          d.provinces = $('select[name="provinces[]"]').val();
		          d.regencies = $('select[name="regencies[]"]').val();
		          d.levels = $('select[name="levels[]"]').val();
		          d.statuses = $('select[name="statuses[]"]').val();
		        }
			},
			columns: [
				{ data: 'DT_RowIndex', name: 'DT_RowIndex', 'searchable': false },
				{ data: 'created_at', name: 'created_at' },
				{ data: 'type', name: 'schools.type' },
				{ data: 'level_name', name: 'school_levels.name' },
				{ data: 'name', name: 'schools.name' },
				{ data: 'province', name: 'schools.province' },
				{ data: 'regency', name: 'schools.regency' },
				{ data: 'headmaster_name', name: 'schools.headmaster_name' },
				{ data: 'pic_name', name: 'pics.name' },
				{ data: 'status_name', name: 'school_statuses.name' },
				{ data: 'code', name: 'schools.code' },
				{ data: 'action', name: 'action' }
			],
			"order": [[ 1, 'desc' ]],
			"columnDefs": [
			{   
          		"targets": [ 0, -1 ], //last column
          		"orderable": false, //set not orderable
      		},
      		],
      		"drawCallback": function(settings) {
      			$('input[name="selectData"], input[name="selectedData[]"]').iCheck({
      				checkboxClass: 'icheckbox_flat-green',
      				radioClass: 'iradio_flat-green',
      				increaseArea: '20%' /* optional */
      			});
      			$('[name="selectData"]').on('ifChecked', function(event){
      				$('[name="selectedData[]"]').iCheck('check');
      			}).on('ifUnchecked', function(event){
      				$('[name="selectedData[]"]').iCheck('uncheck');
      			});
      		},
  		});

  		$('select[name="provinces[]"]').change(function(event) {
			event.preventDefault();
			var provinces = $('select[name="provinces[]"] option:selected').map(function(){
				return $(this).val();
			}).get();
			$('select[name="regencies[]"]').html('');
			if ($(this).val() != '') {
				$.ajax({
					url : "{{ route('get.regency') }}",
					type: "POST",
					dataType: "JSON",
					data: {'_token' : '{{ csrf_token() }}', 'provinces' : provinces},
					success: function(data)
					{
						$.each(data.result, function(key, value) {
							$('select[name="regencies[]"]').append('<option value="'+value+'">'+value+'</option>');
						});
					},
					error: function (jqXHR, textStatus, errorThrown)
					{
						$('select[name="regencies[]"]').html('');
					}
				});
			}
		});

		$('select[name="levels[]"]').change(function(event) {
			event.preventDefault();
			var levels = $('select[name="levels[]"] option:selected').map(function(){
				return $(this).val();
			}).get();
			$('select[name="statuses[]"]').html('');
			if ($(this).val() != '') {
				$.ajax({
					url : "{{ route('get.schoolStatus') }}",
					type: "POST",
					dataType: "JSON",
					data: {'_token' : '{{ csrf_token() }}', 'levels' : levels},
					success: function(data)
					{
						$.each(data.result, function(key, value) {
							$('select[name="statuses[]"]').append('<option value="'+value+'">'+value+'</option>');
						});
					},
					error: function (jqXHR, textStatus, errorThrown)
					{
						$('select[name="statuses[]"]').html('');
					}
				});
			}
		});

		$('[name="deleteData"]').click(function(event) {
			if ($('[name="selectedData[]"]:checked').length > 0) {
				event.preventDefault();
				var selectedData = $('[name="selectedData[]"]:checked').map(function(){
					return $(this).val();
				}).get();
				swal({
			      	title: '{{ __("Are you sure want to delete this data?") }}',
			      	text: '',
			      	icon: 'warning',
			      	buttons: ['{{ __("Cancel") }}', true],
			      	dangerMode: true,
			    })
			    .then((willDelete) => {
			      	if (willDelete) {
			      		$.ajax({
							url : "{{ route('admin.school.destroy') }}",
							type: "DELETE",
							dataType: "JSON",
							data: {"selectedData" : selectedData, "_token" : "{{ csrf_token() }}"},
							success: function(data)
							{
								reloadTable();
							},
							error: function (jqXHR, textStatus, errorThrown)
							{
								if (JSON.parse(jqXHR.responseText).status) {
									swal("{{ __('Failed!') }}", '{{ __("Data cannot be deleted.") }}', "warning");
								} else {
									swal(JSON.parse(jqXHR.responseText).message, "", "error");
								}
							}
						});
			      	}
    			});
			} else {
				swal("{{ __('Please select a data..') }}", "", "warning");
			}
		});
	});

	function reloadTable() {
	    table.ajax.reload(null,false); //reload datatable ajax
	    $('[name="selectData"]').iCheck('uncheck');
	}

	function filter() {
		reloadTable();
		$('#filterModal').modal('hide');
	}
</script>

<!-- Modal -->
<div class="modal fade" id="filterModal" tabindex="-1" role="dialog" aria-labelledby="filterModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="filterModallLabel">{{ __('Filter') }}</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			{{ Form::open(['route' => 'admin.school.export', 'files' => true]) }}
				<div class="modal-body">
					<div class="container-fluid">
						<div class="row">
							{{ Form::bsSelect('col-sm-4', null, 'provinces[]', $provinces, null, __('All Province'), ['multiple' => '']) }}
							{{ Form::bsSelect('col-sm-4', null, 'regencies[]', [], null, __('All Regency'), ['multiple' => '']) }}
							{{ Form::bsSelect('col-sm-4', null, 'levels[]', $levels, null, __('All Level'), ['multiple' => '']) }}
							{{ Form::bsSelect('col-sm-4', null, 'statuses[]', [], null, __('All Status'), ['multiple' => '']) }}
						</div>
					</div>
				</div>
				<div class="modal-footer bg-whitesmoke d-flex justify-content-center">
					{{ Form::submit(__('Export'), ['class' => 'btn btn-primary']) }}
					{{ Form::button(__('Filter'), ['class' => 'btn btn-primary', 'onclick' => 'filter()']) }}
					{{ Form::button(__('Cancel'), ['class' => 'btn btn-secondary', ' data-dismiss' => 'modal']) }}
				</div>
			{{ Form::close() }}
		</div>
	</div>
</div>
@endsection